name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # OPTIONAL: Upload release asset to GitHub Releases
      - name: Build Deployment Artifact
        run: |
          cd test
          qmake test.pro
          make

      - name: Deploy to Server (Placeholder)
        run: |
          echo "Deploying your application..."
          # Example: Upload to server or production location
          # scp ./test user@yourserver:/path/to/deploy/
